#!/bin/bash

source ./arch/functions.sh

cd ./src

make clean

cd .. 

if [ ! -z ${1} ]; then
  if [ ${1} == "-a" ]; then
      rm -rf ./bin
      rm -rf ./Dockerfile
      rm -rf ./docker-compose.yml
      rm -rf ./config.in
      rm -rf ./.slocal
      container=$(check_container)
      if [ ! -z $container ]; then 
          echo "Stopping container..."
          docker stop $container
          echo "Done."
      fi
  else
      echo "Option ${1} does not exist."
      exit
  fi
fi

rm -rf ../.local

rm -rf ./src/Makefile