#!/bin/bash

build_container() {

    docker build -f ./util/docker/Dockerfile -t intel/oneapi-hpckit:1.0 .

    ROOT_DIR=`pwd`

cat << EOF > docker-compose.yml
version: "3.9"
   
services:

  main:
    image: intel/oneapi-hpckit:1.0
    container_name: intel-gnu
    ports:
      - "7777:9000"
    volumes:
      - "${ROOT_DIR}:/home/container"

EOF

cat << EOF > ./bin/connect

#!/bin/bash

HASH_ID=\`docker ps | grep intel-gnu | grep ntel/oneapi-hpckit | cut -d' ' -f1\`

docker exec -it \${HASH_ID} bash

EOF

    YML_FILE="${ROOT_DIR}/docker-compose.yml"
    echo "docker-compose -f ${YML_FILE} up -d" > ./bin/start 

}


DATE=`date`

echo
echo "-------------------------------------------------------"
echo
echo "           Shallow Water Model - Fortran"
echo "  Compilation started at $DATE"
echo
echo "-------------------------------------------------------"
echo



mkdir -p ./bin 

while true; do

     HASH_ID=`docker ps | grep intel-gnu | grep intel/oneapi-hpckit | cut -d' ' -f1`

    if [ -z $HASH_ID ]; then
        read -p " Do you wish to build the code in a docker container? [Y/n] " opt
    else
        opt="Y"
    fi 
    echo
    case $opt in
       "Y")
          build_container
          cd ./bin
          chmod 755 ./start 
          chmod 755 ./connect
          ./start
          cd ..
          cp -Rf ./util/docker/comp.sh .
          docker exec intel-gnu /bin/bash /home/container/comp.sh
          rm -rf ./comp.sh
          break
          ;;
      "n")
          cd ./src
          make
          cd ../bin
          ln -fs ../src/swf.exe .
          cd ..
          break
          ;;
      *)
         echo "ERROR: Option $opt not valid. Try again..."
         echo   
     ;;
    esac
done

if [ ! -f ./src/swf.exe ]; then
  echo
  echo "  ERROR: Compilation failed! "
  echo 
  exit
fi

DATE=`date`
echo
echo "======================================================="
echo 
echo "  Compilation ended at $DATE"
echo
echo "======================================================="
echo





