#!/bin/bash

source ./arch/functions.sh

if [ ! -f "config.in" ]; then 
    echo 
    echo "  ERROR: config.ac was not found!"
    echo "  use ./configure" 
    echo
    exit
fi

source ./config.in

DATE=`date`

echo
echo "-------------------------------------------------------"
echo
echo "           Shallow Water Model - Fortran"
echo "  Compilation started at $DATE"
echo
echo "-------------------------------------------------------"
echo

mkdir -p ./bin 

while true; do

     HASH_ID=`docker ps | grep intel-gnu | grep intel/oneapi-hpckit | cut -d' ' -f1`

    if [[ -f ./.local ]]; then
        opt="n"
    elif [[ -z $HASH_ID ]]; then
        read -p " Do you wish to build the code in a docker container? [Y/n] " opt
    else 
       opt="Y"
    fi
    
    case $opt in
       "Y")
          build_makefile
          build_container
          cd ./bin
          chmod 755 ./start 
          chmod 755 ./connect
          ./start
          cd ..
          cp -Rf ./util/docker/comp.sh .
          docker exec intel-gnu /bin/bash /home/container/comp.sh
          rm -rf ./comp.sh
          break
          ;;
      "n")
          touch ./.local
          build_makefile
          cd ./src
          make
          cd ../bin
          ln -fs ../src/swf.exe .
          cd ..
          break
          ;;
      *)
         echo "ERROR: Option $opt not valid. Try again..."
         echo   
     ;;
    esac

done

cd ./bin 

if [ ! -f ./namelist.input ]; then 
    cp ../util/namelist.input .
fi

cd ..

if [ ! -f ./src/swf.exe ]; then
  echo
  echo "  ERROR: Compilation failed! "
  echo 
  exit
fi

DATE=`date`
echo
echo "======================================================="
echo 
echo "  Compilation ended at $DATE"
echo
echo "======================================================="
echo





